language: python

install:
    - pip install .
    - pip install tox

branches:
    only:
        - master

matrix:
    include:
        - python: 3.6
          env: TOXENV=py36-withcov
        - python: 3.5
          env: TOXENV=py35-withcov

script:
    - tox
