language: python

python:
    - 3.5
    - 3.6

env:
    - TOXENV=py35
    - TOXENV=py36

install:
    - pip install '.[dev]'

branches:
    only:
        - master

matrix:
    exclude:
        - python: 3.6
          env: TOXENV=py35
        - python: 3.5
          env: TOXENV=py36

script:
    - tox
