language: python

python:
    - 3.5
    - 3.6

install:
    - pip install --dev .

branches:
    only:
        - master

matrix:
    include:
        - python: 3.6
          env: TOXENV=py36
        - python: 3.5
          env: TOXENV=py35

script:
    - tox
